version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest ruff
  pre_build:
    commands:
      - ruff --version
      - ruff check . || true
  build:
    commands:
      - pytest -q

artifacts:
  files:
    - "**/*"
  exclude-paths:
    - ".git/**"
    - ".elasticbeanstalk/**"
    - "infra/**"
