version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - pip install pytest ruff

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - ruff --version
      - ruff check . || true
      - ls -la
      - ls -la application.py
      - python -c "import importlib.util; print(importlib.util.find_spec('application'))"

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - export PYTHONPATH=$CODEBUILD_SRC_DIR
      - echo "Running unit/integration tests (moto) ..."
      - python -m pytest -q -m "not aws"
      - |
          if [ "${RUN_AWS_INTEGRATION:-}" = "1" ]; then
            echo "RUN_AWS_INTEGRATION=1 -> Running AWS integration tests ..."
            python -m pytest -q -m aws
          else
            echo "RUN_AWS_INTEGRATION not set -> Skipping AWS integration tests."
          fi

cache:
  paths:
    - "/root/.cache/pip/**/*"          

artifacts:
  files:
    - "**/*"
  exclude-paths:
    - ".git/**"
    - ".elasticbeanstalk/**"
    - "infra/**"
    - ".git/**"
    - ".elasticbeanstalk/**"
    - "infra/**"
    - "tests/**"
    - ".venv/**"
    - "__pycache__/**"
    - ".pytest_cache/**"
    - ".ruff_cache/**"
